import express from 'express';
import { requestLogger } from './middleware/logger';
import healthRouter from './routes/health';
import schoolsRouter from './routes/schools';
import gradesRouter from './routes/grades';
import subjectsRouter from './routes/subjects';
import streamsRouter from './routes/streams';
import classesRouter from './routes/classes';
import peopleRouter from './routes/people';
import learnersRouter from './routes/learners';
import chaptersRouter from './routes/chapters';
import conceptsRouter from './routes/concepts';
import lessonsRouter from './routes/lessons';
import homeworkRouter from './routes/homework';
import learnerFeedbackRouter from './routes/learnerFeedback';
import authRouter from './routes/auth';
import learnerImportRouter from './routes/learnerImport';
import chapterImportRouter from './routes/chapterImport';

const app = express();

app.use(express.json());
app.use(requestLogger);
app.use(authRouter);
app.use(healthRouter);
app.use(schoolsRouter);
app.use(gradesRouter);
app.use(subjectsRouter);
app.use(streamsRouter);
app.use(classesRouter);
app.use(peopleRouter);
app.use(learnersRouter);
app.use(chaptersRouter);
app.use(conceptsRouter);
app.use(lessonsRouter);
app.use(homeworkRouter);
app.use(learnerFeedbackRouter);
app.use(learnerImportRouter);
app.use(chapterImportRouter);

export default app;